
include:
  - board: seeeduino_xiao_ble
    shield: ki-test2_left
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: ki-test2_right
  - board: seeeduino_xiao_ble
    shield: settings_reset
